version: '3.9'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway_1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - clarus-net
    configs:
      - source: init_table
        target: docker-entrypoint-initdb.d/init_table



  app-server:
    image: $ECR_REPO:latest 
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    ports:
      - "80:80"
    networks: 
      - clarus-net
  

networks:
  clarus-net:
    driver: overlay

volumes:
  db-data:

configs:
  init_table:
    file: ./init.sql


